/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Local: () => import('#controllers/auth/local_controller'),
    PasswordReset: () => import('#controllers/auth/password_reset_controller'),
    Tokens: () => import('#controllers/auth/tokens_controller'),
    Vipps: () => import('#controllers/auth/vipps_controller'),
  },
  BranchItems: () => import('#controllers/branch_items_controller'),
  branches: {
    BranchMembership: () => import('#controllers/branches/branch_membership_controller'),
    BranchRelationship: () => import('#controllers/branches/branch_relationship_controller'),
    BranchUpload: () => import('#controllers/branches/branch_upload_controller'),
    Branches: () => import('#controllers/branches/branches_controller'),
  },
  Checkout: () => import('#controllers/checkout_controller'),
  Companies: () => import('#controllers/companies_controller'),
  CustomerItems: () => import('#controllers/customer_items_controller'),
  Dispatch: () => import('#controllers/dispatch_controller'),
  EditableTexts: () => import('#controllers/editable_texts_controller'),
  EmailValidations: () => import('#controllers/email_validations_controller'),
  Items: () => import('#controllers/items_controller'),
  matches: {
    helpers: {
      Generate: () => import('#controllers/matches/helpers/generate'),
      GetMyMatches: () => import('#controllers/matches/helpers/get_my_matches'),
      Lock: () => import('#controllers/matches/helpers/lock'),
      matchFinder: {
        MatchFinder: () => import('#controllers/matches/helpers/match-finder/match-finder'),
        MatchMeetingInfo: () => import('#controllers/matches/helpers/match-finder/match-meeting-info'),
        MatchTestingUtils: () => import('#controllers/matches/helpers/match-finder/match-testing-utils'),
        MatchTypes: () => import('#controllers/matches/helpers/match-finder/match-types'),
        MatchUtils: () => import('#controllers/matches/helpers/match-finder/match-utils'),
      },
      Notify: () => import('#controllers/matches/helpers/notify'),
      Transfer: () => import('#controllers/matches/helpers/transfer'),
    },
    Matches: () => import('#controllers/matches/matches_controller'),
  },
  OpeningHours: () => import('#controllers/opening_hours_controller'),
  OrderHistory: () => import('#controllers/order_history_controller'),
  Orders: () => import('#controllers/orders_controller'),
  Postal: () => import('#controllers/postal_controller'),
  PublicBlidLookup: () => import('#controllers/public_blid_lookup_controller'),
  QuestionsAndAnswers: () => import('#controllers/questions_and_answers_controller'),
  Reminders: () => import('#controllers/reminders_controller'),
  Signatures: () => import('#controllers/signatures_controller'),
  Subjects: () => import('#controllers/subjects_controller'),
  UniqueIds: () => import('#controllers/unique_ids_controller'),
  UniqueItems: () => import('#controllers/unique_items_controller'),
  UserDetail: () => import('#controllers/user_detail_controller'),
  UserProvisioning: () => import('#controllers/user_provisioning_controller'),
  WaitingListEntries: () => import('#controllers/waiting_list_entries_controller'),
}
