// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type {
  MakeTuyauRequest,
  MakeNonSerializedTuyauResponse,
} from "@tuyau/utils/types";
import type { InferInput } from "@vinejs/vine/types";

type TokenPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/auth_validators.ts"))["tokenValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/auth/tokens_controller.ts").default["legacyToken"],
    true
  >;
};
type V2TokenPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/auth_validators.ts"))["tokenValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/auth/tokens_controller.ts").default["token"],
    true
  >;
};
type AuthVippsRedirectGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/auth/vipps_controller.ts").default["redirect"],
    false
  >;
};
type AuthVippsCallbackGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/auth/vipps_controller.ts").default["callback"],
    false
  >;
};
type AuthLocalLoginPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/auth_validators.ts"))["localAuthValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/auth/local_controller.ts").default["login"],
    true
  >;
};
type AuthLocalRegisterPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/auth_validators.ts"))["registerValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/auth/local_controller.ts").default["register"],
    true
  >;
};
type ForgotPasswordPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/auth_validators.ts"))["forgotPasswordValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/auth/password_reset_controller.ts").default["requestPasswordReset"],
    true
  >;
};
type ResetpasswordValidatePost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/auth_validators.ts"))["passwordResetValidValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/auth/password_reset_controller.ts").default["validatePasswordReset"],
    true
  >;
};
type ResetPasswordPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/auth_validators.ts"))["passwordResetValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/auth/password_reset_controller.ts").default["resetPassword"],
    true
  >;
};
type WaitingListEntriesGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/waiting_list_entries_controller.ts").default["getAllWaitingListEntries"],
    false
  >;
};
type WaitingListEntriesPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/waiting_list.ts"))["waitingListEntryValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/waiting_list_entries_controller.ts").default["addWaitingListEntry"],
    true
  >;
};
type WaitinglistentriesIdDelete = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/waiting_list_entries_controller.ts").default["deleteWaitingListEntry"],
    false
  >;
};
type RemindersCountrecipientsPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/reminder.ts"))["reminderValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/reminders_controller.ts").default["countRecipients"],
    true
  >;
};
type RemindersSendPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/reminder.ts"))["reminderValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/reminders_controller.ts").default["remind"],
    true
  >;
};
type V2BranchesPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/branch.ts"))["branchGeneralValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/branches/branch_general_controller.ts").default["add"],
    true
  >;
};
type V2BranchesGeneralIdPatch = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/branch.ts"))["branchGeneralValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/branches/branch_general_controller.ts").default["update"],
    true
  >;
};
type V2BranchesIdPatch = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/branch.ts"))["branchValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/branches/branches_controller.ts").default["update"],
    true
  >;
};
type V2BranchesMembershipsPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/branch_membership.ts"))["branchMembershipValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/branches/branches_controller.ts").default["uploadMemberships"],
    true
  >;
};
type V2BranchesSubjectchoicesPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/subject_choices.ts"))["subjectChoicesValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/branches/branches_controller.ts").default["uploadSubjectChoices"],
    true
  >;
};
type EmailsSendPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/mail_template_sender.ts"))["emailTemplateSenderValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/mail_template_sender_controller.ts").default["sendEmails"],
    true
  >;
};
type V2OrdersOpenordersGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/orders_controller.ts").default["getOpenOrders"],
    false
  >;
};
type V2OrdersCancelorderitemPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/cancel_order_item_validator.ts"))["cancelOrderItemValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/orders_controller.ts").default["cancelOrderItem"],
    true
  >;
};
type EditableTextsGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/editable_texts_controller.ts").default["getAll"],
    false
  >;
};
type EditabletextsKeyIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/editable_texts_controller.ts").default["getByKey"],
    false
  >;
};
type EditableTextsPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/editable_texts_validator.ts"))["editableTextsValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/editable_texts_controller.ts").default["store"],
    true
  >;
};
type EditabletextsIdPatch = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/editable_texts_controller.ts").default["update"],
    false
  >;
};
type EditabletextsIdDelete = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/editable_texts_controller.ts").default["destroy"],
    false
  >;
};
type QuestionsAndAnswersGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/questions_and_answers_controller.ts").default["getAll"],
    false
  >;
};
type QuestionsAndAnswersPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/questions_and_answers_validator.ts"))["questionsAndAnswersValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/questions_and_answers_controller.ts").default["store"],
    true
  >;
};
type QuestionsandanswersIdPatch = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/questions_and_answers_validator.ts"))["questionsAndAnswersValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/questions_and_answers_controller.ts").default["update"],
    true
  >;
};
type QuestionsandanswersIdDelete = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/questions_and_answers_controller.ts").default["destroy"],
    false
  >;
};
type EmailValidationsPost = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/email_validations_controller.ts").default["create"],
    false
  >;
};
type EmailvalidationsIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/email_validations_controller.ts").default["confirm"],
    false
  >;
};
type PublicblidlookupIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/public_blid_lookup_controller.ts").default["lookup"],
    false
  >;
};
type MatchesGeneratePost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/matches.ts"))["matchGenerateValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/matches/matches_controller.ts").default["generate"],
    true
  >;
};
type MatchesNotifyPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/matches.ts"))["matchNotifyValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/matches/matches_controller.ts").default["notify"],
    true
  >;
};
type UsermatchesLockPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/matches.ts"))["matchLockValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/matches/matches_controller.ts").default["lock"],
    true
  >;
};
type MatchesMeGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/matches/matches_controller.ts").default["getMyMatches"],
    false
  >;
};
type MatchesTransferitemPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/matches.ts"))["matchTransferValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/matches/matches_controller.ts").default["transferItem"],
    true
  >;
};
type V2UserdetailsIdIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/user_detail_controller.ts").default["getById"],
    false
  >;
};
type V2UserdetailsMeGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/user_detail_controller.ts").default["getMyDetails"],
    false
  >;
};
type V2UserdetailsPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/user_detail.ts"))["customerUpdateUserDetailsValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/user_detail_controller.ts").default["updateAsCustomer"],
    true
  >;
};
type V2EmployeeUserdetailsIdPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/user_detail.ts"))["employeeUpdateUserDetailsValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/user_detail_controller.ts").default["updateAsEmployee"],
    true
  >;
};
type V2CustomeritemsGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/customer_items_controller.ts").default["getCustomerItems"],
    false
  >;
};
type SignaturesSendIdPost = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/signatures_controller.ts").default["sendSignatureLink"],
    false
  >;
};
type SignaturesMeSendPost = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/signatures_controller.ts").default["sendSignatureLinkAsCustomer"],
    false
  >;
};
type SignaturesValidIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/signatures_controller.ts").default["hasValidSignature"],
    false
  >;
};
type SignaturesGetIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/signatures_controller.ts").default["getSignature"],
    false
  >;
};
type SignaturesSignIdPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/signature.ts"))["signValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/signatures_controller.ts").default["sign"],
    true
  >;
};
type UniqueidsTokenGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/unique_ids_controller.ts").default["getToken"],
    false
  >;
};
type UniqueidsDownloadpdfIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/unique_ids_controller.ts").default["downloadUniqueIdPdf"],
    false
  >;
};
type UsersCreatePost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/user_provisioning.ts"))["userProvisioningValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/user_provisioning_controller.ts").default["createUsers"],
    true
  >;
};
type UniqueitemsAddPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/unique_item.ts"))["uniqueItemsValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/unique_items_controller.ts").default["add"],
    true
  >;
};
type OrderhistoryMeIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/order_history_controller.ts").default["getMyOrder"],
    false
  >;
};
type OrderhistoryMeGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/order_history_controller.ts").default["getMyOrders"],
    false
  >;
};
type CheckoutPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/checkout_validators.ts"))["initializeCheckoutValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/checkout_controller.ts").default["initializeCheckout"],
    true
  >;
};
type CheckoutConfirmIdPost = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/checkout_controller.ts").default["confirmCheckout"],
    false
  >;
};
type CheckoutVippsCallbackPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/checkout_validators.ts"))["vippsCheckoutSessionValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/checkout_controller.ts").default["handleVippsCallback"],
    true
  >;
};
type CheckoutPollIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/checkout_controller.ts").default["pollPayment"],
    false
  >;
};
type SubjectsIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/subjects_controller.ts").default["getBranchSubjects"],
    false
  >;
};
type PostalLookupPostalcodeIdGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/postal_controller.ts").default["lookupPostalCode"],
    false
  >;
};
type V2CompaniesGetHead = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/companies_controller.ts").default["getCompanies"],
    false
  >;
};
type V2CompaniesPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import("../app/validators/companies_validators.ts"))["companyValidator"]
    >
  >;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/companies_controller.ts").default["addCompany"],
    true
  >;
};
type V2CompaniesIdDelete = {
  request: unknown;
  response: MakeNonSerializedTuyauResponse<
    import("../app/controllers/companies_controller.ts").default["deleteCompany"],
    false
  >;
};
export interface ApiDefinition {
  token: {
    $url: {};
    $post: TokenPost;
  };
  v2: {
    token: {
      $url: {};
      $post: V2TokenPost;
    };
    branches: {
      $url: {};
      $post: V2BranchesPost;
      general: {
        ":id": {
          $url: {};
          $patch: V2BranchesGeneralIdPatch;
        };
      };
      ":id": {
        $url: {};
        $patch: V2BranchesIdPatch;
      };
      memberships: {
        $url: {};
        $post: V2BranchesMembershipsPost;
      };
      subject_choices: {
        $url: {};
        $post: V2BranchesSubjectchoicesPost;
      };
    };
    orders: {
      open_orders: {
        $url: {};
        $get: V2OrdersOpenordersGetHead;
        $head: V2OrdersOpenordersGetHead;
      };
      cancel_order_item: {
        $url: {};
        $post: V2OrdersCancelorderitemPost;
      };
    };
    user_details: {
      id: {
        ":detailsId": {
          $url: {};
          $get: V2UserdetailsIdIdGetHead;
          $head: V2UserdetailsIdIdGetHead;
        };
      };
      me: {
        $url: {};
        $get: V2UserdetailsMeGetHead;
        $head: V2UserdetailsMeGetHead;
      };
      $url: {};
      $post: V2UserdetailsPost;
    };
    employee: {
      user_details: {
        ":detailsId": {
          $url: {};
          $post: V2EmployeeUserdetailsIdPost;
        };
      };
    };
    customer_items: {
      $url: {};
      $get: V2CustomeritemsGetHead;
      $head: V2CustomeritemsGetHead;
    };
    companies: {
      $url: {};
      $get: V2CompaniesGetHead;
      $head: V2CompaniesGetHead;
      $post: V2CompaniesPost;
      ":companyId": {
        $url: {};
        $delete: V2CompaniesIdDelete;
      };
    };
  };
  auth: {
    vipps: {
      redirect: {
        $url: {};
        $get: AuthVippsRedirectGetHead;
        $head: AuthVippsRedirectGetHead;
      };
      callback: {
        $url: {};
        $get: AuthVippsCallbackGetHead;
        $head: AuthVippsCallbackGetHead;
      };
    };
    local: {
      login: {
        $url: {};
        $post: AuthLocalLoginPost;
      };
      register: {
        $url: {};
        $post: AuthLocalRegisterPost;
      };
    };
  };
  forgot_password: {
    $url: {};
    $post: ForgotPasswordPost;
  };
  reset_password: {
    validate: {
      $url: {};
      $post: ResetpasswordValidatePost;
    };
    $url: {};
    $post: ResetPasswordPost;
  };
  waiting_list_entries: {
    $url: {};
    $get: WaitingListEntriesGetHead;
    $head: WaitingListEntriesGetHead;
    $post: WaitingListEntriesPost;
    ":id": {
      $url: {};
      $delete: WaitinglistentriesIdDelete;
    };
  };
  reminders: {
    count_recipients: {
      $url: {};
      $post: RemindersCountrecipientsPost;
    };
    send: {
      $url: {};
      $post: RemindersSendPost;
    };
  };
  emails: {
    send: {
      $url: {};
      $post: EmailsSendPost;
    };
  };
  editable_texts: {
    $url: {};
    $get: EditableTextsGetHead;
    $head: EditableTextsGetHead;
    key: {
      ":key": {
        $url: {};
        $get: EditabletextsKeyIdGetHead;
        $head: EditabletextsKeyIdGetHead;
      };
    };
    $post: EditableTextsPost;
    ":id": {
      $url: {};
      $patch: EditabletextsIdPatch;
      $delete: EditabletextsIdDelete;
    };
  };
  questions_and_answers: {
    $url: {};
    $get: QuestionsAndAnswersGetHead;
    $head: QuestionsAndAnswersGetHead;
    $post: QuestionsAndAnswersPost;
    ":id": {
      $url: {};
      $patch: QuestionsandanswersIdPatch;
      $delete: QuestionsandanswersIdDelete;
    };
  };
  email_validations: {
    $url: {};
    $post: EmailValidationsPost;
    ":id": {
      $url: {};
      $get: EmailvalidationsIdGetHead;
      $head: EmailvalidationsIdGetHead;
    };
  };
  public_blid_lookup: {
    ":blid": {
      $url: {};
      $get: PublicblidlookupIdGetHead;
      $head: PublicblidlookupIdGetHead;
    };
  };
  matches: {
    generate: {
      $url: {};
      $post: MatchesGeneratePost;
    };
    notify: {
      $url: {};
      $post: MatchesNotifyPost;
    };
    me: {
      $url: {};
      $get: MatchesMeGetHead;
      $head: MatchesMeGetHead;
    };
    transfer_item: {
      $url: {};
      $post: MatchesTransferitemPost;
    };
  };
  user_matches: {
    lock: {
      $url: {};
      $post: UsermatchesLockPost;
    };
  };
  signatures: {
    send: {
      ":detailsId": {
        $url: {};
        $post: SignaturesSendIdPost;
      };
    };
    me: {
      send: {
        $url: {};
        $post: SignaturesMeSendPost;
      };
    };
    valid: {
      ":detailsId": {
        $url: {};
        $get: SignaturesValidIdGetHead;
        $head: SignaturesValidIdGetHead;
      };
    };
    get: {
      ":detailsId": {
        $url: {};
        $get: SignaturesGetIdGetHead;
        $head: SignaturesGetIdGetHead;
      };
    };
    sign: {
      ":detailsId": {
        $url: {};
        $post: SignaturesSignIdPost;
      };
    };
  };
  unique_ids: {
    token: {
      $url: {};
      $get: UniqueidsTokenGetHead;
      $head: UniqueidsTokenGetHead;
    };
    download_pdf: {
      ":token": {
        $url: {};
        $get: UniqueidsDownloadpdfIdGetHead;
        $head: UniqueidsDownloadpdfIdGetHead;
      };
    };
  };
  users: {
    create: {
      $url: {};
      $post: UsersCreatePost;
    };
  };
  unique_items: {
    add: {
      $url: {};
      $post: UniqueitemsAddPost;
    };
  };
  order_history: {
    me: {
      ":orderId": {
        $url: {};
        $get: OrderhistoryMeIdGetHead;
        $head: OrderhistoryMeIdGetHead;
      };
      $url: {};
      $get: OrderhistoryMeGetHead;
      $head: OrderhistoryMeGetHead;
    };
  };
  checkout: {
    $url: {};
    $post: CheckoutPost;
    confirm: {
      ":orderId": {
        $url: {};
        $post: CheckoutConfirmIdPost;
      };
    };
    vipps: {
      callback: {
        $url: {};
        $post: CheckoutVippsCallbackPost;
      };
    };
    poll: {
      ":orderId": {
        $url: {};
        $get: CheckoutPollIdGetHead;
        $head: CheckoutPollIdGetHead;
      };
    };
  };
  subjects: {
    ":branchId": {
      $url: {};
      $get: SubjectsIdGetHead;
      $head: SubjectsIdGetHead;
    };
  };
  postal: {
    lookup: {
      postal_code: {
        ":postalCode": {
          $url: {};
          $get: PostalLookupPostalcodeIdGetHead;
          $head: PostalLookupPostalcodeIdGetHead;
        };
      };
    };
  };
}
const routes = [
  {
    params: [],
    name: "auth.legacyToken",
    path: "/token",
    method: ["POST"],
    types: {} as TokenPost,
  },
  {
    params: [],
    name: "v2.auth.token",
    path: "/v2/token",
    method: ["POST"],
    types: {} as V2TokenPost,
  },
  {
    params: [],
    name: "auth.vipps.redirect",
    path: "/auth/vipps/redirect",
    method: ["GET", "HEAD"],
    types: {} as AuthVippsRedirectGetHead,
  },
  {
    params: [],
    name: "auth.vipps.callback",
    path: "/auth/vipps/callback",
    method: ["GET", "HEAD"],
    types: {} as AuthVippsCallbackGetHead,
  },
  {
    params: [],
    name: "auth.local.login",
    path: "/auth/local/login",
    method: ["POST"],
    types: {} as AuthLocalLoginPost,
  },
  {
    params: [],
    name: "auth.local.register",
    path: "/auth/local/register",
    method: ["POST"],
    types: {} as AuthLocalRegisterPost,
  },
  {
    params: [],
    name: "auth.password.forgot",
    path: "/forgot_password",
    method: ["POST"],
    types: {} as ForgotPasswordPost,
  },
  {
    params: [],
    name: "auth.password.reset.validate",
    path: "/reset_password/validate",
    method: ["POST"],
    types: {} as ResetpasswordValidatePost,
  },
  {
    params: [],
    name: "auth.password.reset",
    path: "/reset_password",
    method: ["POST"],
    types: {} as ResetPasswordPost,
  },
  {
    params: [],
    name: "waiting_list_entries.getAll",
    path: "/waiting_list_entries",
    method: ["GET", "HEAD"],
    types: {} as WaitingListEntriesGetHead,
  },
  {
    params: [],
    name: "waiting_list_entries.add",
    path: "/waiting_list_entries",
    method: ["POST"],
    types: {} as WaitingListEntriesPost,
  },
  {
    params: ["id"],
    name: "waiting_list_entries.delete",
    path: "/waiting_list_entries/:id",
    method: ["DELETE"],
    types: {} as WaitinglistentriesIdDelete,
  },
  {
    params: [],
    name: "reminders.count_recipients",
    path: "/reminders/count_recipients",
    method: ["POST"],
    types: {} as RemindersCountrecipientsPost,
  },
  {
    params: [],
    name: "reminders.send",
    path: "/reminders/send",
    method: ["POST"],
    types: {} as RemindersSendPost,
  },
  {
    params: [],
    name: "branches.add",
    path: "/v2/branches",
    method: ["POST"],
    types: {} as V2BranchesPost,
  },
  {
    params: ["id"],
    name: "branches.general.update",
    path: "/v2/branches/general/:id",
    method: ["PATCH"],
    types: {} as V2BranchesGeneralIdPatch,
  },
  {
    params: ["id"],
    name: "branches.update",
    path: "/v2/branches/:id",
    method: ["PATCH"],
    types: {} as V2BranchesIdPatch,
  },
  {
    params: [],
    name: "branches.addMemberships",
    path: "/v2/branches/memberships",
    method: ["POST"],
    types: {} as V2BranchesMembershipsPost,
  },
  {
    params: [],
    name: "branches.addSubjectChoices",
    path: "/v2/branches/subject_choices",
    method: ["POST"],
    types: {} as V2BranchesSubjectchoicesPost,
  },
  {
    params: [],
    name: "emails.send",
    path: "/emails/send",
    method: ["POST"],
    types: {} as EmailsSendPost,
  },
  {
    params: [],
    name: "open_orders.get",
    path: "/v2/orders/open_orders",
    method: ["GET", "HEAD"],
    types: {} as V2OrdersOpenordersGetHead,
  },
  {
    params: [],
    name: "open_orders.cancel",
    path: "/v2/orders/cancel_order_item",
    method: ["POST"],
    types: {} as V2OrdersCancelorderitemPost,
  },
  {
    params: [],
    name: "editable_texts.getAll",
    path: "/editable_texts",
    method: ["GET", "HEAD"],
    types: {} as EditableTextsGetHead,
  },
  {
    params: ["key"],
    name: "editable_texts.getByKey",
    path: "/editable_texts/key/:key",
    method: ["GET", "HEAD"],
    types: {} as EditabletextsKeyIdGetHead,
  },
  {
    params: [],
    name: "editable_texts.store",
    path: "/editable_texts",
    method: ["POST"],
    types: {} as EditableTextsPost,
  },
  {
    params: ["id"],
    name: "editable_texts.update",
    path: "/editable_texts/:id",
    method: ["PATCH"],
    types: {} as EditabletextsIdPatch,
  },
  {
    params: ["id"],
    name: "editable_texts.destroy",
    path: "/editable_texts/:id",
    method: ["DELETE"],
    types: {} as EditabletextsIdDelete,
  },
  {
    params: [],
    name: "questions_and_answers.getAll",
    path: "/questions_and_answers",
    method: ["GET", "HEAD"],
    types: {} as QuestionsAndAnswersGetHead,
  },
  {
    params: [],
    name: "questions_and_answers.store",
    path: "/questions_and_answers",
    method: ["POST"],
    types: {} as QuestionsAndAnswersPost,
  },
  {
    params: ["id"],
    name: "questions_and_answers.update",
    path: "/questions_and_answers/:id",
    method: ["PATCH"],
    types: {} as QuestionsandanswersIdPatch,
  },
  {
    params: ["id"],
    name: "questions_and_answers.destroy",
    path: "/questions_and_answers/:id",
    method: ["DELETE"],
    types: {} as QuestionsandanswersIdDelete,
  },
  {
    params: [],
    name: "email_validations.create",
    path: "/email_validations",
    method: ["POST"],
    types: {} as EmailValidationsPost,
  },
  {
    params: ["id"],
    name: "email_validations.confirm",
    path: "/email_validations/:id",
    method: ["GET", "HEAD"],
    types: {} as EmailvalidationsIdGetHead,
  },
  {
    params: ["blid"],
    name: "blid.lookup",
    path: "/public_blid_lookup/:blid",
    method: ["GET", "HEAD"],
    types: {} as PublicblidlookupIdGetHead,
  },
  {
    params: [],
    name: "matches.generate",
    path: "/matches/generate",
    method: ["POST"],
    types: {} as MatchesGeneratePost,
  },
  {
    params: [],
    name: "matches.notify",
    path: "/matches/notify",
    method: ["POST"],
    types: {} as MatchesNotifyPost,
  },
  {
    params: [],
    name: "matches.lock",
    path: "/user_matches/lock",
    method: ["POST"],
    types: {} as UsermatchesLockPost,
  },
  {
    params: [],
    name: "matches.getMyMatches",
    path: "/matches/me",
    method: ["GET", "HEAD"],
    types: {} as MatchesMeGetHead,
  },
  {
    params: [],
    name: "matches.transfer_item",
    path: "/matches/transfer_item",
    method: ["POST"],
    types: {} as MatchesTransferitemPost,
  },
  {
    params: ["detailsId"],
    name: "user_detail.getById",
    path: "/v2/user_details/id/:detailsId",
    method: ["GET", "HEAD"],
    types: {} as V2UserdetailsIdIdGetHead,
  },
  {
    params: [],
    name: "user_detail.getMyDetails",
    path: "/v2/user_details/me",
    method: ["GET", "HEAD"],
    types: {} as V2UserdetailsMeGetHead,
  },
  {
    params: [],
    name: "user_detail.updateAsCustomer",
    path: "/v2/user_details",
    method: ["POST"],
    types: {} as V2UserdetailsPost,
  },
  {
    params: ["detailsId"],
    name: "user_detail.updateAsEmployee",
    path: "/v2/employee/user_details/:detailsId",
    method: ["POST"],
    types: {} as V2EmployeeUserdetailsIdPost,
  },
  {
    params: [],
    name: "customer_items.get",
    path: "/v2/customer_items",
    method: ["GET", "HEAD"],
    types: {} as V2CustomeritemsGetHead,
  },
  {
    params: ["detailsId"],
    name: "signatures.send.link",
    path: "/signatures/send/:detailsId",
    method: ["POST"],
    types: {} as SignaturesSendIdPost,
  },
  {
    params: [],
    name: "signatures.me.send",
    path: "/signatures/me/send",
    method: ["POST"],
    types: {} as SignaturesMeSendPost,
  },
  {
    params: ["detailsId"],
    name: "signatures.valid",
    path: "/signatures/valid/:detailsId",
    method: ["GET", "HEAD"],
    types: {} as SignaturesValidIdGetHead,
  },
  {
    params: ["detailsId"],
    name: "signatures.get",
    path: "/signatures/get/:detailsId",
    method: ["GET", "HEAD"],
    types: {} as SignaturesGetIdGetHead,
  },
  {
    params: ["detailsId"],
    name: "signatures.sign",
    path: "/signatures/sign/:detailsId",
    method: ["POST"],
    types: {} as SignaturesSignIdPost,
  },
  {
    params: [],
    name: "unique_ids.token",
    path: "/unique_ids/token",
    method: ["GET", "HEAD"],
    types: {} as UniqueidsTokenGetHead,
  },
  {
    params: ["token"],
    name: "unique_ids.download.pdf",
    path: "/unique_ids/download_pdf/:token",
    method: ["GET", "HEAD"],
    types: {} as UniqueidsDownloadpdfIdGetHead,
  },
  {
    params: [],
    name: "users.create",
    path: "/users/create",
    method: ["POST"],
    types: {} as UsersCreatePost,
  },
  {
    params: [],
    name: "unique_items.add",
    path: "/unique_items/add",
    method: ["POST"],
    types: {} as UniqueitemsAddPost,
  },
  {
    params: ["orderId"],
    name: "order_history.get.my.order",
    path: "/order_history/me/:orderId",
    method: ["GET", "HEAD"],
    types: {} as OrderhistoryMeIdGetHead,
  },
  {
    params: [],
    name: "order_history.get.my.orders",
    path: "/order_history/me",
    method: ["GET", "HEAD"],
    types: {} as OrderhistoryMeGetHead,
  },
  {
    params: [],
    name: "checkout.initialize",
    path: "/checkout",
    method: ["POST"],
    types: {} as CheckoutPost,
  },
  {
    params: ["orderId"],
    name: "checkout.confirm",
    path: "/checkout/confirm/:orderId",
    method: ["POST"],
    types: {} as CheckoutConfirmIdPost,
  },
  {
    params: [],
    name: "checkout.vipps.callback",
    path: "/checkout/vipps/callback",
    method: ["POST"],
    types: {} as CheckoutVippsCallbackPost,
  },
  {
    params: ["orderId"],
    name: "checkout.poll",
    path: "/checkout/poll/:orderId",
    method: ["GET", "HEAD"],
    types: {} as CheckoutPollIdGetHead,
  },
  {
    params: ["branchId"],
    name: "subjects.get.branch.subjects",
    path: "/subjects/:branchId",
    method: ["GET", "HEAD"],
    types: {} as SubjectsIdGetHead,
  },
  {
    params: ["postalCode"],
    name: "lookup.postal.code",
    path: "/postal/lookup/postal_code/:postalCode",
    method: ["GET", "HEAD"],
    types: {} as PostalLookupPostalcodeIdGetHead,
  },
  {
    params: [],
    name: "companies.get",
    path: "/v2/companies",
    method: ["GET", "HEAD"],
    types: {} as V2CompaniesGetHead,
  },
  {
    params: [],
    name: "companies.add",
    path: "/v2/companies",
    method: ["POST"],
    types: {} as V2CompaniesPost,
  },
  {
    params: ["companyId"],
    name: "companies.delete",
    path: "/v2/companies/:companyId",
    method: ["DELETE"],
    types: {} as V2CompaniesIdDelete,
  },
  {
    params: ["id"],
    name: "collection.branches.getId",
    path: "/branches/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.branches.getAll",
    path: "/branches",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.branches.post",
    path: "/branches",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.branches.patch",
    path: "/branches/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.branchitems.getId",
    path: "/branchitems/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.branchitems.post",
    path: "/branchitems",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.branchitems.patch",
    path: "/branchitems/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.branchitems.getAll",
    path: "/branchitems",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.branchitems.delete",
    path: "/branchitems/:id",
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.customeritems.getId",
    path: "/customeritems/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.customeritems.patch",
    path: "/customeritems/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.customeritems.post",
    path: "/customeritems",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.customeritems.operation.generate-report.post",
    path: "/customeritems/generate-report",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.customeritems.getAll",
    path: "/customeritems",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.deliveries.post",
    path: "/deliveries",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.deliveries.getAll",
    path: "/deliveries",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.deliveries.getId",
    path: "/deliveries/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.deliveries.patch",
    path: "/deliveries/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.deliveries.delete",
    path: "/deliveries/:id",
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.items.getId",
    path: "/items/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.items.getAll",
    path: "/items",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.items.post",
    path: "/items",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.items.patch",
    path: "/items/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.openinghours.getId",
    path: "/openinghours/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.openinghours.getAll",
    path: "/openinghours",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.openinghours.post",
    path: "/openinghours",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.openinghours.patch",
    path: "/openinghours/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.orders.post",
    path: "/orders",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.orders.operation.rapid-handout.post",
    path: "/orders/rapid-handout",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.orders.delete",
    path: "/orders/:id",
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.orders.patch",
    path: "/orders/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.orders.operation.place.patch",
    path: "/orders/:id/place",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.orders.operation.confirm.patch",
    path: "/orders/:id/confirm",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.orders.getId",
    path: "/orders/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.orders.operation.get_customer_orders.getId",
    path: "/orders/:id/get_customer_orders",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.orders.getAll",
    path: "/orders",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.payments.post",
    path: "/payments",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.payments.getAll",
    path: "/payments",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.payments.getId",
    path: "/payments/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.payments.patch",
    path: "/payments/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.payments.delete",
    path: "/payments/:id",
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.userdetails.getId",
    path: "/userdetails/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.userdetails.operation.valid.getId",
    path: "/userdetails/:id/valid",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.userdetails.operation.permission.getId",
    path: "/userdetails/:id/permission",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.userdetails.patch",
    path: "/userdetails/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.userdetails.delete",
    path: "/userdetails/:id",
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.userdetails.getAll",
    path: "/userdetails",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.messages.post",
    path: "/messages",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.messages.operation.sendgrid-events.post",
    path: "/messages/sendgrid-events",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.messages.operation.twilio-sms-events.post",
    path: "/messages/twilio-sms-events",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.messages.getAll",
    path: "/messages",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.messages.getId",
    path: "/messages/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.messages.delete",
    path: "/messages/:id",
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.invoices.getId",
    path: "/invoices/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.invoices.getAll",
    path: "/invoices",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.invoices.post",
    path: "/invoices",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.invoices.patch",
    path: "/invoices/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.companies.getAll",
    path: "/companies",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.companies.getId",
    path: "/companies/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.companies.post",
    path: "/companies",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.companies.patch",
    path: "/companies/:id",
    method: ["PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.companies.delete",
    path: "/companies/:id",
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.uniqueitems.post",
    path: "/uniqueitems",
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.uniqueitems.getId",
    path: "/uniqueitems/:id",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: "collection.uniqueitems.operation.active.getId",
    path: "/uniqueitems/:id/active",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "collection.uniqueitems.getAll",
    path: "/uniqueitems",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition,
};
