packages:
  - frontend
  - backend

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - '@swc/core'
  - argon2
  - canvas
  - esbuild
  - inotify
  - puppeteer
  - sharp
