export const BlSchemaName = {
  Branches: "branches",
  BranchItems: "branchitems",
  Companies: "companies",
  CustomerItems: "customeritems",
  Deliveries: "deliveries",
  Invoices: "invoices",
  Items: "items",
  Messages: "messages",
  Orders: "orders",
  Payments: "payments",
  Signatures: "signatures",
  StandMatches: "stand_matches",
  UniqueItems: "uniqueitems",
  Users: "users",
  UserDetails: "userdetails",
  UserMatches: "user_matches",
} as const satisfies Record<string, string>;
