import type { Order } from "#shared/order/order";
import { StorageService } from "#services/storage_service";
import env from "#start/env";
import createClient from "openapi-fetch";
import type { paths } from "#services/kustom/openapi/checkout";
import { TranslationService } from "#services/translation_service";
import { DateService } from "#services/legacy/date.service";
import { DateTime } from "luxon"; // generated by openapi-typescript

const KUSTOM_BASE_URL =
  env.get("API_ENV") === "production"
    ? "https://api.kustom.co/"
    : "https://api.playground.kustom.co/";

const client = createClient<paths>({
  baseUrl: KUSTOM_BASE_URL,
  headers: {
    Authorization: `Basic ${env.get("KUSTOM_KEY").release()}`,
  },
});

export const KustomCheckoutService = {
  async createOrder(order: Order, isDeliveryFree: boolean) {
    console.log(isDeliveryFree); // TODO: use this
    const userDetail = await StorageService.UserDetails.get(order.customer);
    const items = await Promise.all(
      order.orderItems.map((oi) => StorageService.Items.get(oi.item)),
    );
    const nameParts = userDetail.name.split(" ");
    const givenName = nameParts.length > 1 ? nameParts.slice(0, -1).join(" ") : userDetail.name;
    const familyName = nameParts.length > 1 ? nameParts.at(-1) : undefined;
    const address = {
      given_name: givenName,
      family_name: familyName,
      email: userDetail.email,
      phone: userDetail.phone,
      street_address: userDetail.address,
      postal_code: userDetail.postCode,
      city: userDetail.postCity,
      country: "NO",
    };
    return await client.POST("/checkout/v3/orders", {
      body: {
        purchase_country: "no",
        purchase_currency: "NOK",
        locale: "no-NO",
        order_amount: order.amount * 100,
        order_tax_amount: 0,
        order_lines: order.orderItems.map((orderItem) => {
          const priceInMinors = orderItem.amount * 100;
          return {
            type: "physical",
            reference: orderItem.item,
            name: `${orderItem.title} - ${TranslationService.translateOrderItemTypeImperative(orderItem.type)} ${orderItem.info?.to ? DateService.format(orderItem.info?.to, "Europe/Oslo", "DD/MM/YYYY") : ""}`,
            quantity: 1,
            unit_price: priceInMinors,
            tax_rate: 0,
            total_amount: priceInMinors,
            total_tax_amount: 0,
            shipping_attributes: {
              weight:
                Math.round(
                  Number(items.find((item) => item.id === orderItem.item)?.info.weight) * 1000,
                ) || 1000,
            },
          };
        }),
        billing_address: address,
        shipping_address: address,
        customer: {
          date_of_birth: DateTime.fromJSDate(userDetail.dob).toISODate() ?? undefined,
        },
        merchant_urls: {
          terms: `${env.get("CLIENT_URI")}/info/policies/terms`,
          checkout: `${env.get("CLIENT_URI")}/kasse/betaling/v2`,
          confirmation: `https://${env.get("API_ENV") === "production" ? "" : "staging."}boklisten.no/kasse/betaling/status/v2`, // TODO: make it possible to use localhost
          push: `https://${env.get("API_ENV") === "production" ? "" : "staging."}api.boklisten.no/kustom/push`, // TODO: implement this endpoint
        },
        merchant_reference1: order.id,
        options: {
          auto_capture: true,
        },
      },
    });
  },
  async getOrder(kustomOrderId: string) {
    return await client.GET(`/checkout/v3/orders/{order_id}`, {
      params: {
        path: {
          order_id: kustomOrderId,
        },
      },
    });
  },
};
