/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class EditableTextSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'text', 'updatedAt'] as const
  $columns = EditableTextSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare text: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OpeningHourSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'from', 'id', 'to', 'updatedAt'] as const
  $columns = OpeningHourSchema.$columns
  @column()
  declare branchId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare from: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare to: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuestionAndAnswerSchema extends BaseModel {
  static $columns = ['answer', 'createdAt', 'id', 'question', 'updatedAt'] as const
  $columns = QuestionAndAnswerSchema.$columns
  @column()
  declare answer: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare question: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
