/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/checkout/v3/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an order
         * @description To create a new order simply provide a JSON object with the applicable properties.<br>The location of the newly created checkout order can be found in the location header of the response.<br>Please note: This is the url that should be used for future interactions (read and update) with the order, i.e. do not construct the order url based on the order id.
         */
        post: operations["createOrderMerchant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/v3/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order details
         * @description Get the full details of a Kustom Checkout order.
         */
        get: operations["readOrderMerchant"];
        put?: never;
        /**
         * Update an order
         * @description To update an order simply provide a JSON object with the properties you want to update. Properties not provided in the request will stay the same.<br>Please note: an order can only be updated when the status is checkout_incomplete
         */
        post: operations["updateOrderMerchant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/v3/orders/{order_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abort an order
         * @description Mark an order as aborted.
         */
        post: operations["abortOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeliveryDetailsV1: {
            /** @description Carrier product name */
            carrier?: string;
            /** @description Type of shipping class */
            class?: string;
            product?: components["schemas"]["ProductV1"];
            timeslot?: components["schemas"]["TimeslotV1"];
            pickup_location?: components["schemas"]["PickupLocationV1"];
        };
        PickupLocationV1: {
            /** @description Id */
            id?: string;
            /** @description Name of the location */
            name?: string;
            address?: components["schemas"]["address"];
        };
        ProductV1: {
            /** @description Carrier product name */
            name?: string;
            /** @description Carrier product identifier */
            identifier?: string;
        };
        TimeslotV1: {
            /** @description Id */
            id?: string;
            /** @description Start time */
            start?: string;
            /** @description End time */
            end?: string;
        };
        address: {
            /**
             * @description Given name.
             * @example John
             */
            given_name?: string;
            /**
             * @description Family name.
             * @example Doe
             */
            family_name?: string;
            /**
             * @description Organization name. Only applicable for orders with customer.type="organization".
             * @example Acme Corporation
             */
            organization_name?: string;
            /**
             * @description E-mail address.
             * @example john@doe.com
             */
            email?: string;
            /**
             * @description Title.<p>Valid values for UK:</p><ul><li><em>Mr</em></li><li><em>Ms</em></li><li><em>Mrs</em></li><li><em>Miss</em></li></ul><p>Valid values for DACH:</p><ul><li><em>Herr</em></li><li><em>Frau</em></li></ul><p>Valid values for NL:</p><ul><li><em>Dhr.</em></li><li><em>Mevr.</em></li></ul>
             * @example Mr
             */
            title?: string;
            /**
             * @description Street address, first line. (Street name and number)
             * @example Lombard St 10
             */
            street_address?: string;
            /**
             * @description Street address, second line. (Apartment number, suite, etc.)
             * @example Apt 214
             */
            street_address2?: string;
            /**
             * @description Street name. Only applicable in DE/AT/NL. Do not combine with street_address. See <b>streetNumber</b>.
             * @example Lombard St
             */
            street_name?: string;
            /**
             * @description Street number. Only applicable in DE/AT/NL. Do not combine with street_address. See <b>streetName</b>.
             * @example 10
             */
            street_number?: string;
            /**
             * @description House extension. Only applicable in NL
             * @example B
             */
            house_extension?: string;
            /**
             * @description Postal/post code.
             * @example 90210
             */
            postal_code?: string;
            /**
             * @description City.
             * @example Beverly Hills
             */
            city?: string;
            /**
             * @description State or Region.
             * @example CA
             */
            region?: string;
            /**
             * @description Phone number.
             * @example 333444555
             */
            phone?: string;
            /**
             * @description ISO 3166 alpha-2. Country.
             * @example US
             */
            country?: string;
            /**
             * @description Care of.
             * @example C/O
             */
            care_of?: string;
        };
        attachment: {
            /**
             * @description The content of the extra merchant data which should be presented as a string inside this property. The body should be an object containing any of the keys and sub objects described below serialised to JSON. More information on that object can be found [here](https://docs.kustom.co/contents/api/api-basics/extra-merchant-data).
             * @example {"hotel_reservation_details": [{"pnr": "VH67899","hotel_intinerary": [{"hotel_name": "Hotel ltd.","address": {"street_address": "Storgatan 3","postal_code": "113 35","city": "Stockholm","country": "Sweden"},"start_time": "2019-01-31T15:00:00Z","end_time": "2019-01-31T15:30:00Z","number_of_rooms": 2,"ticket_delivery_method": "email","ticket_delivery_recipient": "jonas.larlsson@kustom.co","hotel_price": 23050,"class": "Business","passenger_id": [1]}],"passengers": [{"id": 1,"title": "mr","first_name": "Adam","last_name": "Adamson"}],"insurance": [{"insurance_company": "Insurance Company X","insurance_type": "travel","insurance_price": 0}],"affiliate_name": "TradeMaxi AB"}],"air_reservation_details": [{"pnr": "VH67899","intinerary": [{"departure": "ARN","departure_city": "Stockholm","arrival": "NCE","arrival_city": "Nice","carrier": "SK","segment_price": 34000,"departure_date": "2019-01-30T15:00:00Z","ticket_delivery_method": "email","ticket_delivery_recipient": "jonas.larlsson@kustom.co","passenger_id": [1]}],"passengers": [{"id": 1,"title": "mr","first_name": "Adam","last_name": "Adamson"}],"insurance": [{"insurance_company": "Insurance Company X","insurance_type": "travel","insurance_price": 0}],"affiliate_name": "TradeMaxi AB"}],"customer_account_info": [{"unique_account_identifier": "12345","account_registration_date": "2016-01-24T15:00:00Z","account_last_modified": "2017-01-24T15:00:00Z"}],"payment_history_full": [{"payment_option": "card","number_paid_purchases": 2,"total_amount_paid_purchases": 1234,"date_of_last_paid_purchase": "2018-01-24T15:00:00Z","date_of_first_paid_purchase": "2018-01-24T15:00:00Z"}]}
             */
            body: string;
            /**
             * @description The content type of the body. It is usually represented as "application/vnd.klarna.internal.emd-v2+json"
             * @example application/vnd.klarna.internal.emd-v2+json
             */
            content_type: string;
        };
        checkbox: {
            /**
             * @description Text that will be displayed to the consumer aside the checkbox. Links and formatting can be added using Markdown. (max 1000 characters)
             * @example Please add me to the newsletter list, read more here \[link\](http://www.google.com)
             */
            text: string;
            /** @description Default state of the additional checkbox. It will use this value when loaded for the first time. */
            checked: boolean;
            /** @description Whether it is required for the consumer to check the additional checkbox box or not in order to complete the purchase. */
            required: boolean;
        };
        "checkbox-v2": {
            /**
             * @description Text that will be displayed to the consumer aside the checkbox. Links and formatting can be added using Markdown. (max 1000 characters)
             * @example Please add me to the newsletter list, read more here \[link\](http://www.google.com)
             */
            text: string;
            /** @description Default state of the additional checkbox. It will use this value when loaded for the first time. */
            checked: boolean;
            /** @description Whether it is required for the consumer to check the additional checkbox box or not in order to complete the purchase. */
            required: boolean;
            /**
             * @description Identifier used when presenting data back to merchant
             * @example newsletter_opt_in
             */
            id: string;
        };
        customer: {
            /**
             * @description The default supported value is 'person'. If B2B is enabled for the merchant, the value may be "organization".
             * @example person
             */
            type?: string;
            /**
             * @description Customer's gender - 'male' or 'female'.
             * @example male
             */
            gender?: string;
            /**
             * @description Customer's date of birth. The format is 'yyyy-mm-dd'. ISO 8601 date.
             * @example 1995-10-20
             */
            date_of_birth?: string;
            /**
             * @description "The organization's official registration id (organization number).
             *
             *     Note: Applicable only for B2B orders."
             * @example 556737-0431
             */
            organization_registration_id?: string;
            /** @description Organization VAT ID. Only applies for b2b orders. */
            vat_id?: string;
        };
        dimensions: {
            /**
             * Format: int64
             * @description The product's height as used in the merchant's webshop. Non-negative. Measured in millimeters.
             * @example 100
             */
            height?: number;
            /**
             * Format: int64
             * @description The product's width as used in the merchant's webshop. Non-negative. Measured in millimeters.
             * @example 100
             */
            width?: number;
            /**
             * Format: int64
             * @description The product's length as used in the merchant's webshop. Non-negative. Measured in millimeters.
             * @example 100
             */
            length?: number;
        };
        gui: {
            /**
             * @description An array of options to define the checkout behaviour. Supported options: minimal_confirmation.
             *
             *     The gui object is an array of options to modify checkout client ui behaviours.
             *
             *     Examples: ["minimal_confirmation"]
             */
            options?: string[];
        };
        merchant_requested: {
            /** @description Informs whether the additional_checkbox is checked or not, when applicable. */
            readonly additional_checkbox?: boolean;
            /** @description Informs whether the additional_checkboxes is checked or not, when applicable. */
            readonly additional_checkboxes?: components["schemas"]["merchant_requested_checkbox"][];
        };
        merchant_requested_checkbox: {
            id?: string;
            checked?: boolean;
        };
        merchant_urls: {
            /**
             * @description URL for the terms and conditions page of the merchant. The URL will be displayed inside the Kustom Checkout iFrame.(max 2000 characters)
             *     Example: "https://merchant.com/terms"
             * @example https://www.example.com/terms.html
             */
            terms: string;
            /**
             * @description URL for the checkout page of the merchant. (max 2000 characters)
             *     Example: "https://merchant.com/checkout"
             * @example https://www.example.com/checkout.html
             */
            checkout: string;
            /**
             * @description URL of the merchant confirmation page. The consumer will be redirected back to the confirmation page if the authorization is successful after the customer clicks on the 'Place Order' button inside checkout. The special characters of the confirmation URL should be encoded, e.g. the "space" character should be written as "%20". Then, on top of that, the whole confirmation URL should be encoded. E.g. the "space" character should become "%2520". (max 2000 characters)
             *     Example: "https://merchant.com/confirmation"
             * @example https://www.example.com/confirmation.html
             */
            confirmation: string;
            /**
             * @description URL that will be used for push notification when an order is completed. Should be different than checkout and confirmation URLs. (max 2000 characters)
             *     Example: "https://merchant.com/push"
             * @example https://www.example.com/api/push
             */
            push: string;
            /**
             * @description URL that will be requested for final merchant validation. (must be https, max 2000 characters)
             *     Example: "https://merchant.com/validation"
             * @example https://www.example.com/api/validation
             */
            validation?: string;
            /**
             * @description URL for notifications on pending orders. (max 2000 characters)
             *     Example: "https://merchant.com/notification/{checkout.order.id}"
             * @example https://www.example.com/api/pending
             */
            notification?: string;
            /**
             * @description URL for the cancellation terms page of the merchant. The URL will be displayed in the email that is sent to the customer after the order is captured.(max 2000 characters)
             *     Example: "https://merchant.com/terms/cancelation"
             * @example https://www.example.com/terms/cancellation.html
             */
            cancellation_terms?: string;
            /**
             * @description URL for shipping option update. (must be https, max 2000 characters)
             *     Example: "https://merchant.com/shippingoptionupdate"
             * @example https://www.example.com/api/shipment
             */
            shipping_option_update?: string;
            /**
             * @description URL for shipping, tax and purchase currency updates. Will be called on address changes. (must be https, max 2000 characters)
             *     Example: "https://merchant.com/addressupdate"
             * @example https://www.example.com/api/address
             */
            address_update?: string;
            /**
             * @description URL for shipping, tax and purchase currency updates. Will be called on billing or shipping country changes. (must be https, max 2000 characters)
             *     Example: "https://merchant.com/countrychange"
             * @example https://www.example.com/api/country
             */
            country_change?: string;
        };
        options: {
            /** @description If true, validate callback must get a positive response to not stop purchase. Default: false. */
            require_validate_callback_success?: boolean;
            /**
             * @description Acquiring channel for the order. The possible values are:
             *     <ul><li><em>ECOMMERCE for "E-commerce"</em></li><li><em>IN_STORE for "Purchase in boutique"</em></li><li><em>Default : ECOMMERCE</em></li></ul>
             */
            acquiring_channel?: string;
            /** @description If true, VAT is not displayed in Checkout's Order Summary page. */
            vat_removed?: boolean;
            /** @description If true, the consumer can enter different billing and shipping addresses. Default: false, except for purchase_country DE where default is: true */
            allow_separate_shipping_address?: boolean;
            /**
             * @description Color for the buttons within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
             * @example #FF9900
             */
            color_button?: string;
            /**
             * @description Color for the text inside the buttons within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
             * @example #FF9900
             */
            color_button_text?: string;
            /**
             * @description Color for the checkboxes within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
             * @example #FF9900
             */
            color_checkbox?: string;
            /**
             * @description Color for the checkboxes checkmark within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
             * @example #FF9900
             */
            color_checkbox_checkmark?: string;
            /**
             * @description Color for the headers within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
             * @example #FF9900
             */
            color_header?: string;
            /**
             * @description Color for the hyperlinks within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
             * @example #FF9900
             */
            color_link?: string;
            /**
             * @description Color for the background within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
             * @example #FF9900
             */
            color_background?: string;
            /** @description If true, the consumer cannot skip date of birth. Default: false */
            date_of_birth_mandatory?: boolean;
            /** @description If true, the consumer are able to enter date of birth, but can skip it. Default: false */
            date_of_birth_optional?: boolean;
            /**
             * @description A message that will be presented on the confirmation page under the headline "Delivery" (max 255 characters).
             * @example Delivered within 1-3 working days
             */
            shipping_details?: string;
            /** @description If specified to false, title becomes optional. Only available for orders for country GB. */
            title_mandatory?: boolean;
            additional_checkbox?: components["schemas"]["checkbox"];
            /** @description If true, the user cannot skip national identification number in SE, NO, FI and DK. Default: false. In order to read the national identification number in the validation callback, please contact Kustom's merchant support. */
            national_identification_number_mandatory?: boolean;
            /**
             * @description Additional merchant defined field. e.g. Extra terms and conditions to show.
             *
             *     Example: "ADDITIONAL MERCHANT TERMS! \[terms link\](https://merchant.com/extra_terms)"
             */
            additional_merchant_terms?: string;
            /** @description If false, the consumer can skip the phone. Only available for orders in DACH countries. */
            phone_mandatory?: boolean;
            /**
             * @description Radius for the border of elements within the iFrame.
             * @example 5
             */
            radius_border?: string;
            /**
             * @description A list of allowed customer types. Supported types: <b>person</b> & <b>organization</b>.
             *     Example: ["person","organization"]
             */
            allowed_customer_types?: string[];
            /** @description If true, the Order Detail subtotals view is expanded when the Kustom Checkout iFrame is loaded. Default: false */
            show_subtotal_detail?: boolean;
            additional_checkboxes?: components["schemas"]["checkbox-v2"][];
            /** @description Enable verification of National Identification Numbers only in Sweden and Norway. This option also make the national identification number mandatory. (Not applicable for countries outside of Sweden and Norway) */
            verify_national_identification_number?: boolean;
            /** @description Allow merchant to trigger auto capturing. */
            auto_capture?: boolean;
            /** @description If true, a client side validation is needed to complete the purchase */
            require_client_validation?: boolean;
            /** @description If true, a optional VAT registration number field will be shown in the address form. Only applies for b2b orders. */
            show_vat_registration_number_field?: boolean;
        };
        order: {
            /**
             * @description Unique order ID that will be used for the entire lifecycle of the order. (max 255 characters)
             * @example f3392f8b-6116-4073-ab96-e330819e2c07
             */
            readonly order_id?: string;
            /**
             * @description The merchant name (max 255 characters).
             * @example Women's Fashion
             */
            readonly name?: string;
            /**
             * @description The purchase country of the merchant's store. The format to be used is ISO 3166 alpha-2. Eg: GB, SE, DE, US, etc.
             *
             *     Note: purchase country and currency need to match the defined merchant configuration. For global configuration see more details [here](../checkout/use-cases/selling-to-multiple-countries.md)
             * @example US
             */
            purchase_country: string;
            /**
             * @description The purchase currency of the merchant's store. The format to be used is ISO 4217. Eg: USD, EUR, SEK, GBP, etc.
             *
             *     Note: purchase country and currency need to match the defined merchant configuration. For global configuration see more details [here](../checkout/use-cases/selling-to-multiple-countries.md)
             * @example USD
             */
            purchase_currency: string;
            /**
             * @description Used to define the language and region of the customer. RFC 1766 customer's locale.
             * @example en-US
             */
            locale: string;
            /**
             * @description The current status of the order. The status will be 'incomplete' until the customer has been successfully authorized.
             * @example CHECKOUT_INCOMPLETE
             */
            status?: string;
            billing_address?: components["schemas"]["address"];
            shipping_address?: components["schemas"]["address"];
            /**
             * Format: int64
             * @description Total amount of the order including tax and any available discounts. The value should be in non-negative minor units.
             *
             *     Example: 25 Euros should be 2500.
             * @example 50000
             */
            order_amount: number;
            /**
             * Format: int64
             * @description Total tax amount of the order. The value should be in non-negative minor units.
             *
             *     Example: 25 Euros should be 2500.
             * @example 4545
             */
            order_tax_amount: number;
            /** @description An array containing list of line items that are part of this order. Maximum of 1000 line items could be processed in a single order. */
            order_lines: components["schemas"]["order_line"][];
            customer?: components["schemas"]["customer"];
            merchant_urls?: components["schemas"]["merchant_urls"];
            /**
             * @description The HTML snippet that is used to render the checkout in an iframe.
             * @example <div id='klarna-checkout-container'><script>alert('Initializing Kustom Checkout');</script></div>
             */
            readonly html_snippet?: string;
            /**
             * @description Used for storing merchant's internal order number or other reference. If set, will be shown on the confirmation page as "order number" . The value is also available in the settlement files. (max 255 characters).
             *     Example: "45aa52f387871e3a210645d4"
             * @example 45aa52f387871e3a210645d4
             */
            merchant_reference1?: string;
            /**
             * @description Used for storing merchant's internal order number or other reference. The value is available in the settlement files. (max 255 characters).
             *     Example: "45aa52f387871e3a210645d4"
             * @example 45aa52f387871e3a210645d4
             */
            merchant_reference2?: string;
            /**
             * Format: date-time
             * @description ISO 8601 datetime. The date and time when the order has been created. The format will be as follows:
             *     "yyyy-mm-ddThh:mm:ssZ"
             */
            readonly started_at?: string;
            /**
             * Format: date-time
             * @description ISO 8601 datetime. The date and time when the order has been completed. The format will be as follows:
             *     "yyyy-mm-ddThh:mm:ssZ"
             */
            readonly completed_at?: string;
            /**
             * Format: date-time
             * @description ISO 8601 datetime. The date and time when the order was last modified. The format will be as follows:
             *     "yyyy-mm-ddThh:mm:ssZ"
             */
            readonly last_modified_at?: string;
            options?: components["schemas"]["options"];
            attachment?: components["schemas"]["attachment"];
            /** @description List of external payment methods that will be displayed as part of payment methods in the checkout. */
            external_payment_methods?: components["schemas"]["payment_provider"][];
            /**
             * @description List of external checkouts that will be displayed as part of payment methods in the checkout.
             *     The image_url is required, and the image size has to be 276x48px
             */
            external_checkouts?: components["schemas"]["payment_provider"][];
            /**
             * @description List of allowed shipping countries for this order in ISO-3166 alpha-2 format.
             *
             *     If specified, the customer will be able to change the shipping country in the checkout and you will be notified through 'address_update' callback or the 'shipping_address_change' javascript event.
             *
             *     If not specified then the default value will be the purchase country.
             *
             *     Example: look at billing_countries example.
             */
            shipping_countries?: string[];
            /** @description A list of shipping options available for this order. */
            shipping_options?: components["schemas"]["shipping_option"][];
            /**
             * @description Pass through field to send any information about the order to be used later for reference while retrieving the order details (max 6000 characters).
             * @example {"marketplace_seller_info":[{"product_category":"Women's Fashion","product_name":"Women Sweatshirt"}]}
             */
            merchant_data?: string;
            gui?: components["schemas"]["gui"];
            merchant_requested?: components["schemas"]["merchant_requested"];
            selected_shipping_option?: components["schemas"]["shipping_option"];
            /**
             * @description Indicates whether this purchase will create a token that can be used by the merchant to create recurring purchases. This must be enabled for the merchant to use. Default: false
             *
             *     Depending on specified country, recurring could be used for the following payment methods: Klarna Pay Later, Direct Debit, Card, Apple Pay, Google Pay.
             */
            recurring?: boolean;
            /** @description Token to be used when creating recurring orders. */
            readonly recurring_token?: string;
            /** @description Description to be added to the recurring order. */
            readonly recurring_description?: string;
            /**
             * @description List of allowed billing countries for this order.
             *     If specified, the customer will be able to change the billing country in the checkout and you will be notified through 'country_change' callback or the 'billing_address_change' javascript event.
             *     If not specified but shipping_countries is specified, will use same values as shipping_countries.
             *     If not specified and shipping_countries is not specified, then the default value will be the purchase country.
             *
             *     Example: ["AD", "AE", "AG", "AI", "AL", "AM", "AQ", "AR", "AS", "AT", "AU", "AW", "AX", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BJ", "BL", "BM", "BN", "BO", "BQ", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CF", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ER", "ES", "ET", "FI", "FJ", "FK", "FM", "FO", "FR", "GA", "GB", "GD", "GE", "GF", "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GR", "GS", "GT", "GU", "GY", "HK", "HN", "HR", "HU", "ID", "IE", "IL", "IM", "IN", "IS", "IT", "JE", "JM", "JO", "JP", "KE", "KG", "KI", "KM", "KN", "KR", "KW", "KY", "KZ", "LA", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK", "MK", "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ", "OM", "PA", "PE", "PF", "PG", "PH", "PK", "PL", "PM", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW", "SA", "SB", "SC", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SR", "ST", "SV", "SX", "SZ", "TC", "TF", "TG", "TH", "TJ", "TK", "TL", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VG", "VI", "VN", "VU", "WF", "WS", "XK", "YT", "ZA", "ZM", "ZW"]"
             */
            billing_countries?: string[];
            /**
             * @description Extra information added to the order.
             *
             *     Example: ["dangerous_goods", "bulky"]
             */
            tags?: string[];
        };
        order_line: {
            /**
             * @description Type of the order line item. The possible values are:<ul><li><em>physical (physical good)</em></li><li><em>discount</em></li><li><em>shipping_fee</em></li><li><em>sales_tax (depends on the country/city, usually called VAT)</em></li><li><em>digital (digital good)</em></li><li><em>gift_card</em></li><li><em>store_credit (credit from the merchant)</em></li><li><em>surcharge (extra charge)</em></li></ul>
             * @example physical
             */
            type?: string;
            /**
             * @description Article number, SKU or similar. (max 255 characters)
             * @example 19-402-USA
             */
            reference?: string;
            /**
             * @description Descriptive name of the order line item (max 255 characters)
             * @example Red T-Shirt
             */
            name: string;
            /**
             * Format: int64
             * @description Non-negative number. Quantity of the order line item.
             * @example 5
             */
            quantity: number;
            /**
             * @description Describes the subscription.
             *     Including subscription details will also change the buy button to inform the user that they will be subscribing.
             *     (Only applicable for recurring orders)
             */
            subscription?: components["schemas"]["subscription"];
            /**
             * @description Unit used to describe the quantity, e.g. kg, pcs... If defined has to be 1-8 characters
             * @example pcs
             */
            quantity_unit?: string;
            /**
             * Format: int64
             * @description Minor units. Includes tax, excludes discount. (max value: 100000000).
             *
             *     Example: 100 Euros should be 10000.
             * @example 10000
             */
            unit_price: number;
            /**
             * Format: int64
             * @description Non-negative value. The percentage value is represented with two implicit decimals. (max 10000)
             *
             *     Example: 25% should be 2500.
             * @example 1000
             */
            tax_rate: number;
            /**
             * Format: int64
             * @description Minor units. Includes tax and discount.
             *
             *     Example: 25 euros should be 2500
             *     Value = (quantity x unit_price) - total_discount_amount.
             *     (max value: 100000000)
             * @example 50000
             */
            total_amount: number;
            /**
             * Format: int64
             * @description Non-negative minor units. Includes tax.
             *
             *     Example: 25 euros should be 2500
             * @example 0
             */
            total_discount_amount?: number;
            /**
             * Format: int64
             * @description Must be within ±1 of total_amount - total_amount \* 10000 / (10000 + tax_rate). Negative when type is discount.
             * @example 4545
             */
            total_tax_amount: number;
            /**
             * @description Property used to store additional metadata per item that will be returned whenever an order is read from Kustom. Pass through field. (max 1024 characters).
             * @example {"marketplace_seller_info":[{"product_category":"Women's Fashion","product_name":"Women Sweatshirt"}]}
             */
            merchant_data?: string;
            /**
             * @description URL to the product page that can be later embedded in communications between Kustom and the customer. (max 1024 characters)
             * @example https://www.example.com/products/f2a8d7e34
             */
            product_url?: string;
            /**
             * @description URL to an image that can be later embedded in communications between Kustom and the customer. (max 1024 characters)
             *
             *     Improves post-purchase customer experiences.
             * @example https://www.exampleobjects.com/product-image-1200x1200.jpg
             */
            image_url?: string;
            product_identifiers?: components["schemas"]["product_identifiers"];
            shipping_attributes?: components["schemas"]["shipping_attributes"];
        };
        payment_provider: {
            /**
             * @description The name of the payment provider. (max 255 characters)
             * @example PayhereUs
             */
            name: string;
            /**
             * Format: int64
             * @description Minor units. Includes tax.
             */
            fee?: number;
            /**
             * @description Short description of the payment method. This is displayed below the selected payment method. (max 500 characters)
             * @example an American company operating a worldwide online payments system
             */
            description?: string;
            /** @description If specified, limits the method to the listed countries (alpha 2 codes). */
            countries?: string[];
            /**
             * @description Controls label of buy button<ul><li>continue</li><li>complete</li></ul>
             * @example continue
             */
            label?: string;
            /**
             * @description URL to redirect to. (must be https, min 7, max 2000 characters)
             * @example https://www.example.com/us/start
             */
            redirect_url: string;
            /**
             * @description URL to an image to display. (must be https, max 2000 characters)
             * @example https://www.exampleobjects.com/product-image-1200x1200.jpg
             */
            image_url?: string;
        };
        product_identifiers: {
            /**
             * @description The product's brand name as generally recognized by consumers. If no brand is available for a product, do not supply any value.
             * @example Intel
             */
            brand?: string;
            /**
             * @description Color to be shown to the end customer (max 64 characters).
             * @example Blue
             */
            color?: string;
            /**
             * @description The product's category path as used in the merchant's webshop. Include the full and most detailed category and separate the segments with ' > '. (max 750 characters)
             *
             *     Example: "Electronics Store > Computers & Tablets > Desktops"
             * @example Electronics Store > Computers & Tablets > Desktops
             */
            category_path?: string;
            /**
             * @description The product's Global Trade Item Number (GTIN). Common types of GTIN are EAN, ISBN or UPC. Exclude dashes and spaces, where possible
             * @example 735858293167
             */
            global_trade_item_number?: string;
            /**
             * @description The product's Manufacturer Part Number (MPN), which - together with the brand - uniquely identifies a product. Only submit MPNs assigned by a manufacturer and use the most specific MPN possible
             * @example BOXNUC5CPYH
             */
            manufacturer_part_number?: string;
            /**
             * @description Size to be shown to the end customer (max 64 characters).
             * @example Medium
             */
            size?: string;
        };
        selected_addon: {
            type?: string;
            /** Format: int64 */
            price?: number;
            external_id?: string;
            user_input?: string;
        };
        shipping_attributes: {
            /**
             * Format: int64
             * @description The product's weight as used in the merchant's webshop. Non-negative. Measured in grams.
             * @example 1000
             */
            weight?: number;
            dimensions?: components["schemas"]["dimensions"];
            /** @description The product's extra features, example ["dangerous_goods", "bulky"] */
            tags?: string[];
        };
        shipping_option: {
            /**
             * @description id
             * @example express_priority
             */
            id: string;
            /**
             * @description Name.
             * @example EXPRESS 1-2 Days
             */
            name: string;
            /**
             * @description Description.
             * @example Delivery by 4:30 pm
             */
            description?: string;
            /**
             * @description Promotion name. To be used if this shipping option is promotional.
             * @example Christmas Promotion
             */
            promo?: string;
            /**
             * Format: int64
             * @description Price including tax.
             */
            price: number;
            /** @description If true, this option will be preselected when checkout loads. Default: false */
            preselected?: boolean;
            /**
             * Format: int64
             * @description Tax amount.
             */
            tax_amount: number;
            /**
             * Format: int64
             * @description Non-negative. In percent, two implicit decimals. I.e 2500 = 25%.
             */
            tax_rate: number;
            /**
             * @description Shipping method. Possible values:<ul><li>PickUpStore</li><li>Home</li><li>BoxReg</li><li>BoxUnreg</li><li>PickUpPoint</li><li>Own</li><li>Postal</li><li>DHLPackstation</li><li>Digital</li></ul> If DHLPackstation is selected the correct form will be displayed.
             * @example PickUpStore
             */
            shipping_method?: string;
            delivery_details?: components["schemas"]["DeliveryDetailsV1"];
            /**
             * @description TMS reference. Required to map completed orders to shipments reserved in TMS.
             * @example a1b2c3d4-e4f6-g7h8-i9j0-k1l2m3n4o5p6
             */
            tms_reference?: string;
            /**
             * @description TOS ID. Required to map completed orders to shipments reserved via Ingrid.
             * @example 01K7HJZHY22AAX6PNV5DPXNZQF
             */
            tos_id?: string;
            selected_addons?: components["schemas"]["selected_addon"][];
        };
        /**
         * @description Describes the subscription.
         *     Including subscription details will also change the buy button to inform the user that they will be subscribing.
         *     (Only applicable for recurring orders)
         */
        subscription: {
            /**
             * @description The name of the subscription product.
             *
             *     Example: "Premium Account"
             */
            name?: string;
            /**
             * @description The cadence unit for this.
             *
             *     Example: "DAY"
             * @enum {string}
             */
            interval: "DAY" | "WEEK" | "MONTH" | "YEAR";
            /**
             * Format: int32
             * @description The number of intervals.
             *
             *     Example: 30
             */
            interval_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        order: {
            content: {
                "application/json": components["schemas"]["order"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createOrderMerchant: {
        parameters: {
            query?: never;
            header?: {
                "Kustom-Partner"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["order"];
        responses: {
            /** @description successful operation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["order"];
                };
            };
            /** @description We were unable to create an order with the provided data. Some field constraint was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description You were not authorized to execute this operation. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readOrderMerchant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["order"];
                };
            };
            /** @description You were not authorized to execute this operation. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Merchant was not activated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description We did not find any order with given ID. You need to create a new order. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateOrderMerchant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["order"];
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["order"];
                };
            };
            /** @description We were unable to update an order with the provided data. Some field constraint was violated. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description You were not authorized to execute this operation. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description You tried to modify a read only resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description We did not find any order with given ID. You need to create a new order. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    abortOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["order"];
                };
            };
            /** @description You tried to modify a read only resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description We did not find any order with given ID. You need to create a new order. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
