/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch shipping details
         * @description <p>Use this endpoint to get expected delivery, prices, service categories and additional information.</p><h3>Measurements</h3><p>For cargo services(5100, 5300, 9100, CARGO), Weight is mandatory and one of the Volume / Load Meter / Dimensions / Number of Pallets is mandatory.</p><p>Note: The prices for our revised services depends on volumetric weight: 5000, 5100, 5300, 5600, 5800, 4850 plus return services 9000, 9100, 9300 or 9600. For these services, dimensions (L/W/H) is needed to calculate the expected price correctly. Dimensions are also used to decide if handling fee or specialgoods fee will apply to the shipment. You might leave dimensions empty in your request, but be aware that returned prices might be incorrect.</p>
         */
        post: operations["products"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Additional service */
        AdditionalServiceInputType: {
            /** @description Additional service id */
            id: string | null;
        };
        Consignment: {
            /** @description List of all packages in the consignment */
            packages: components["schemas"]["Package"][] | null;
            /** @description Two-letter ISO-3166-1 country code of which consignment is sent from */
            fromCountryCode: string | null;
            /** @description The postal code the consignment is sent from */
            fromPostalCode: string | null;
            /** @description Two-letter ISO-3166-1 country code of which consignment is sent to */
            toCountryCode: string | null;
            /** @description The postal code the consignment is to be delivered to */
            toPostalCode: string | null;
            /** @description The street name and number the consignment is to be delivered to */
            addressLine?: string | null;
            /** @description The city the consignment is to be delivered to */
            toCity?: string | null;
            shippingDate?: components["schemas"]["ShippingDate"] | null;
            /** @description Additional services to be added */
            additionalServices?: components["schemas"]["AdditionalServiceInputType"][] | null;
            dangerousGoods?: components["schemas"]["DangerousGoods"] | null;
            /** @description International commercial terms */
            incoterms?: string | null;
            /** @description The pickup point id to which the consignment is to be shipped to. Only relevant for parcel products */
            pickupPointId?: string | null;
            /** @description List of pickup points for which estimated delivery time should be calculated for (if varue of 'WithEstimatedDeliveryTime' is true). If not provided, the default pickup point for the receiver's postal code will be used. */
            pickupPoints?: components["schemas"]["PickupPointInputType"][] | null;
            /** @description List of all services price and lead times should be calculated for */
            products: components["schemas"]["ProductIdType"][] | null;
            /** @description Your internal reference to this consignment (you may calculate several consignment at the same time) */
            id?: string | null;
        };
        DangerousGoods: {
            /** @description List of dangerous goods ADR-codes */
            unNumbers: string[] | null;
        };
        /** @description Describing the package details */
        Package: {
            /**
             * Format: double
             * @description Height of the package in centimeters
             */
            height?: number | null;
            /**
             * Format: double
             * @description Width of the package in centimeters
             */
            width?: number | null;
            /**
             * Format: double
             * @description Length of the package in centimeters. The highest value of height, width and length will always be used as length
             */
            length?: number | null;
            /**
             * Format: double
             * @description The weight of the package in gram
             */
            grossWeight?: number | null;
            /** @description The volume of the package in cubic decimeters */
            volume?: string | null;
            /**
             * @description Set to true if you know the package price will be adjusted for special volume. Typically used for roll or other weirdly shaped packages.
             * @default false
             */
            volumeSpecial: boolean | null;
            /**
             * @description Set to true if you know the package/pallet is non-stackable
             * @default false
             */
            nonStackable: boolean | null;
            /**
             * Format: int32
             * @description Number of pallets. Only applicable for cargo products
             * @default 0
             */
            numberOfPallets: number | null;
            /**
             * Format: double
             * @description Loading meters. Only applicable for cargo products
             */
            loadMeter?: number | null;
            /** @description Your internal reference to this package (you may estimate several packages at the same time) */
            id?: string | null;
        };
        /** @description Pickup point */
        PickupPointInputType: {
            /** @description Pickup point id */
            id: string | null;
        };
        /** @description A service you want price and lead times calculated for */
        ProductIdType: {
            /** @description The service id */
            id: string | null;
            /** @description The mybring API customer number. Different customer numbers exist for different services, therefore the customer number is specified for each requested service. If a valid customer number is supplied, net prices will be returned for the specified service. Otherwise list (gross) prices is returned. */
            customerNumber?: string | null;
            /**
             * @description Which party will pay for the shipment
             * @enum {string}
             */
            Payer?: "SENDER" | "RECEIVER" | "THIRD_PARTY";
            /** @description Required field when requesting non standard courier products. Represents the customer specific service code */
            nonStandardCourierService?: string | null;
        };
        ShippingDate: {
            year: string | null;
            month: string | null;
            day: string | null;
            hour?: string | null;
            minute?: string | null;
        };
        Shipping_guide_request: {
            /** @description List of consignments */
            consignments: components["schemas"]["Consignment"][];
            /**
             * @description Language in which human-readable message should be returned.
             * @default NO
             * @enum {string|null}
             */
            language: "NO" | "SE" | "SV" | "DA" | "EN" | null;
            /**
             * @description Controls whether prices should be calculated. If customerNumber is supplied, the authenticated user requires the financial role with the provided customer
             * @default true
             */
            withPrice: boolean | null;
            /**
             * @description Controls whether lead times should be calculated or not
             * @default true
             */
            withExpectedDelivery: boolean | null;
            /**
             * @description Return detailed information about requested service(s)
             * @default true
             */
            withGuiInformation: boolean | null;
            /**
             * Format: int32
             * @description Number of alternative delivery dates to be suggested
             * @default 0
             */
            numberOfAlternativeDeliveryDates: number | null;
            /**
             * @description Should the parcel be registered using EDI when shipped. Note that this flag may affect price and which services are available
             * @default true
             */
            edi: boolean | null;
            /**
             * @description Will the parcel be delivered at a post office when shipped
             * @default false
             */
            postingAtPostoffice: boolean | null;
            /**
             * @description Extended lead time information, including predicted arrivar time at pickup point. Only supported for a limited set of services
             * @default false
             */
            withEstimatedDeliveryTime: boolean | null;
            /**
             * @description Return environmental data about fossil free and electric transportation used on the shipments transport legs
             * @default false
             */
            withEnvironmentalData: boolean | null;
        };
        AdditionalServicePriceType: {
            additionalServiceId: string | null;
            additionalServiceDescription: string | null;
            additionalServicePrice: components["schemas"]["DetailedPriceType"] | null;
            additionalServiceCodeFromProductionSystem: string | null;
        };
        AgreementAttributeType: {
            agreementNumber?: string | null;
        };
        AlternativeDeliveryDateType: {
            /** @description Number of working days until delivery */
            workingDays: string | null;
            shippingDate: components["schemas"]["DateAndTimeType"] | null;
            /**
             * Format: dd.MM.yyyy
             * @description Formatted expected delivery date
             */
            formattedExpectedDeliveryDate?: string | null;
            expectedDeliveryDate: components["schemas"]["ExpectedDeliveryDateType"] | null;
        };
        CargoAgreementAttributesType: {
            /** @description Agreement name */
            agreementName: string | null;
            /** @description Agreement number */
            agreementNumber: string | null;
            /** @description Sub agreement number */
            subAgreementNumber: string | null;
            /** @description Sub agreement name */
            subAgreementName: string | null;
            /** @description Agreement price */
            price: string | null;
        };
        CargoSpecificEdiParametersType: {
            /** @description Dispatch agent number */
            dispatchAgentNumber: string | null;
            /** @description Cargo transport type */
            cargoTransportType?: string | null;
            /** @description Cargo product */
            cargoProduct?: string | null;
        };
        ConsignmentOutputType: {
            /** @description <p>The requested services results.</p><p>ShippingGuide will never remove services from the request if unable to calculate any of the requested data. It will either return the requested data or a service level error code along with a description.</p> */
            products?: components["schemas"]["ProductOutputType"][] | null;
            /** @description The consignment id */
            consignmentId?: string | null;
        };
        CourierSpecificEdiParametersType: {
            /** @description Department */
            department: string | null;
            /** @description Operations id */
            operationsID: string | null;
            /** @description Number of kilometers */
            numberOfKilometers?: string | null;
            /** @description Order start time */
            orderStartTime?: string | null;
        };
        DateAndTimeType: {
            year: string | null;
            month: string | null;
            day: string | null;
            hour?: string | null;
            minute?: string | null;
        };
        DayTimeType: {
            hour: string | null;
            minute: string | null;
        };
        DetailedPriceType: {
            amountWithoutVAT: string | null;
            vat: string | null;
            amountWithVAT: string | null;
        };
        EdiType: {
            courier?: components["schemas"]["CourierSpecificEdiParametersType"] | null;
            quickpack?: components["schemas"]["QuickpackSpecificEdiParametersType"] | null;
            cargo?: components["schemas"]["CargoSpecificEdiParametersType"] | null;
        };
        EnvironmentalDataDetailsType: {
            /**
             * Format: double
             * @description Share of electric vehicles used on this transportation leg
             */
            electric?: number | null;
            /**
             * Format: double
             * @description Share of bio-diesel vehicles used on this transportation leg
             */
            bio?: number | null;
        };
        ErrorType: {
            /**
             * @description General error code type
             * @enum {string}
             */
            code: "NOT_FOUND" | "FORBIDDEN" | "CONFLICT" | "UNAUTHORIZED" | "INVALID_ARGUMENT" | "INVALID_MEASUREMENTS" | "INTERNAL_ERROR";
            /**
             * @description Error code
             * @enum {string}
             */
            errorCode: "EXTERNAL_SERVICE_UNAVAILABLE" | "CUSTOMER_NOT_SPECIFIED" | "CUSTOMER_NOT_FOUND" | "CUSTOMER_NO_FINANCIAL_ACCESS" | "CUSTOMER_FORBIDDEN" | "CUSTOMER_NOT_APPLICABLE_FOR_PRODUCT" | "PACKAGE_TOO_BIG" | "REQUIRES_WEIGHT" | "PRICE_CALCULATION_FAILED" | "INVALID_COUNTRY_PAIR" | "OIL_EXPRESS_NOT_AVAILABLE" | "MULTIPLE_PACKAGE_NOT_SUPPORTED" | "PRODUCT_SKIPPED_COURIER" | "PRODUCT_NOT_SUPPORTED" | "NON_STANDARD_COURIER_SERVICE_REQUIRED" | "NUMBER_OF_PALLETS_AND_LOAD_METERS_NOT_SUPPORTED" | "PRODUCT_UNKNOWN" | "COURIER_PRODUCT_NOT_AVAILABLE" | "MAIN_CUSTOMER_NUMBER_REQUIRED" | "INTERNAL_ERROR" | "OUTSIDE_COVERAGE_AREA" | "OUTSIDE_COVERAGE_AREA_SPECIAL_POSTAL_CODE" | "OUTSIDE_COVERAGE_AREA_FROM_SPECIAL_POSTAL_CODE" | "OUTSIDE_COVERAGE_AREA_TO_SPECIAL_POSTAL_CODE" | "OUTSIDE_COVERAGE_AREA_PO_BOX" | "OUTSIDE_COVERAGE_AREA_TO_PO_BOX" | "OUTSIDE_COVERAGE_AREA_FROM_SVALBARD" | "OUTSIDE_COVERAGE_AREA_TO_SVALBARD" | "OUTSIDE_COVERAGE_AREA_EXPRESS" | "PACKAGE_NOT_WITHIN_WEIGHT_LIMIT" | "CONSIGNMENT_NOT_WITHIN_WEIGHT_LIMIT" | "CONSIGNMENT_CHARGEABLE_WEIGHT_LIMIT_EXCEEDED" | "WEIGHT_AND_VOLUME_OR_DIMENSIONS_OR_PALLETS_OR_LOAD_METER_REQUIRED" | "WEIGHT_OR_DIMENSIONS_OR_VOLUME_REQUIRED" | "WEIGHT_OR_DIMENSIONS_REQUIRED" | "PACKAGE_WEIGHT_OR_VOLUME_BELOW_MINIMUM_LIMIT" | "TOO_MANY_PACKAGES" | "PACKAGE_DIMENSIONS_TOO_SMALL" | "INVALID_ARGUMENTS" | "SHIPPING_DATE_MAX_10_DAYS_INTO_FUTURE" | "VAS_REQUIRES_CUSTOMER_NUMBER" | "INVALID_VAS_COMBINATION" | "INVALID_CUSTOMER_VAS_COMBINATION" | "INVALID_SERVICE_VAS_COMBINATION" | "SHIPPING_DATE_MUST_BE_CURRENT_DATE_OR_FUTURE" | "SATURDAY_DELIVERY_NOT_AVAILABLE_FOR_ROUTE";
            /** @description Human-readable description of the error that occurred */
            description: string;
        };
        EstimatedDeliveryTime: {
            /** @description Pickup point id. Either provided in the request or fetched as default pickup point for recipient postal code */
            pickupPointId: string | null;
            /** @description Pickup point name */
            pickupPointName?: string | null;
            /** @description Delivery time window start time at the specified pickup point */
            deliveryStartTime?: string | null;
            /** @description Delivery time window end time at the specified pickup point */
            deliveryEndTime?: string | null;
            /** @description Formatted expected delivery date */
            formattedExpectedDeliveryDate?: string | null;
            /** @description Formatted shipping date */
            shippingDate?: string | null;
            /**
             * Format: int32
             * @description Number of working days until delivery
             */
            workingDays?: number | null;
        };
        ExpectedDeliveryDateType: {
            year: string | null;
            month: string | null;
            day: string | null;
            hour?: string | null;
            minute?: string | null;
            timeSlots?: components["schemas"]["TimeSlotType"][] | null;
        };
        ExpectedDeliveryType: {
            /** @description The expected number of working days to deliver the shipment */
            workingDays: string | null;
            /**
             * Format: HH:mm
             * @description The deadline for booking a shipment to the given destination. Only relevant for OIL_EXPRESS.
             */
            bookingCutoffTime?: string | null;
            /**
             * @deprecated
             * @description If there is known inaccuracy in the calculated lead time, this message will contain a human readable text explaining the deviation
             */
            userMessage: string;
            /**
             * Format: dd.MM.YYYY HH:mm
             * @description Expected delivery date/time formatted as dd.MM.YYYY HH:mm
             */
            formattedExpectedDeliveryDate?: string | null;
            expectedDeliveryDate?: components["schemas"]["ExpectedDeliveryDateType"] | null;
            /** @description Alternative delivery dates */
            alternativeDeliveryDates?: components["schemas"]["AlternativeDeliveryDateType"][] | null;
            /**
             * Format: dd.MM.yyyy
             * @description Formatted earliest pickup date
             */
            formattedEarliestPickupDate?: string | null;
            earliestPickupDate?: components["schemas"]["DateAndTimeType"] | null;
            latestPickupTime?: components["schemas"]["DateAndTimeType"] | null;
            sameDayDelivery?: components["schemas"]["SameDayDeliveryType"] | null;
        };
        GuiInformationType: {
            /** @description Main display category */
            mainDisplayCategory: string | null;
            /** @description Sub display category */
            subDisplayCategory: string | null;
            /** @description Is this service trackable */
            trackable?: boolean | null;
            /**
             * @description Logo type to be used with this service
             * @enum {string|null}
             */
            logo?: "POSTEN" | "BRING" | null;
            /** @description URL to a suitable logo in svg format */
            logoUrl?: string | null;
            /** @description Service display name */
            displayName: string | null;
            /** @description Service name */
            productName: string | null;
            /** @description Service description */
            descriptionText: string | null;
            /** @description Service help text */
            helpText: string | null;
            /** @description Service short name */
            shortName: string | null;
            /** @description URL to service description page */
            productURL: string | null;
            /** @description Service delivery type */
            deliveryType: string | null;
            /** @description Service max weight in kgs */
            maxWeightInKgs: string | null;
            /**
             * @description Default pickup point for the requested toPostalCode. Only relevant for pickup point services SERVICEPAKKE, 5800 and 3067
             * @example Pakkeboks Store Brevik. Åpningstider Man - Søn: 0000-2359
             */
            closestPickupPoint?: string | null;
            /** @description URL to logo for labelling service as environmental friendly */
            environmentalLogoUrl?: string | null;
            /** @description URL to tag for labelling services as environmental friendly */
            environmentalTagUrl?: string | null;
        };
        PriceType: {
            priceWithoutAdditionalServices: components["schemas"]["DetailedPriceType"] | null;
            /** @description Additional service prices */
            additionalServices?: components["schemas"]["AdditionalServicePriceType"][] | null;
            priceWithAdditionalServices: components["schemas"]["DetailedPriceType"] | null;
            /** @description Cargo agreement price attributes */
            cargoAgreementPrices?: components["schemas"]["CargoAgreementAttributesType"][] | null;
            agreementAttributes?: components["schemas"]["AgreementAttributeType"] | null;
            /** @description Currency code for all prices */
            currencyCode?: string | null;
            /** @description Only used for net prices in the scenario where net price calculation fails. If true, returned net price will be equal to list price, or a partially discounted price (i.e. a value between the list price and the correct net price) */
            netPriceFailed?: boolean | null;
        };
        PriceZonesType: {
            /**
             * Format: int32
             * @description The total number of price zones used during price calculation
             */
            totalZoneCount?: number | null;
        };
        PricesType: {
            listPrice?: components["schemas"]["PriceType"] | null;
            netPrice?: components["schemas"]["PriceType"] | null;
            zones?: components["schemas"]["PriceZonesType"] | null;
        };
        ProductOutputType: {
            /** @description The service id */
            id: string | null;
            /** @description The mybring API customer number */
            customerNumber?: string | null;
            /** @description Backend system production code. This code is required when producing valid EDI messages during ordering. */
            productionCode?: string | null;
            /**
             * @deprecated
             * @description Sorting code. Only relevant for home delivery services with Norway as destination.
             */
            sortingCode?: string | null;
            /**
             * @deprecated
             * @description Sorting direction. Only relevant for home delivery services with Norway as destination.
             */
            sortingDirection?: string | null;
            /**
             * @deprecated
             * @description Indicates whether the shipment is being delivered with fossil free transportation or not. Only relevant for HD-services
             */
            greenDelivery?: boolean | null;
            /**
             * Format: double
             * @description The calculated volumetric weight (chargeable weight)
             */
            shippingWeight?: number | null;
            guiInformation?: components["schemas"]["GuiInformationType"] | null;
            price?: components["schemas"]["PricesType"] | null;
            expectedDelivery?: components["schemas"]["ExpectedDeliveryType"] | null;
            /** @description Estimated delivery times at provided pickup point ids. Only relevant when withEstimatedDeliveryTime flag is set for services delivered to pickup point. */
            estimatedDeliveryTimes?: components["schemas"]["EstimatedDeliveryTime"][] | null;
            /** @description Estimated delivery times at provided pickup point ids. Only relevant when withEstimatedDeliveryTime flag is set for services delivered to pickup point. */
            environmentalData?: components["schemas"]["TransportLegEnvironmentalDataType"][] | null;
            edi?: components["schemas"]["EdiType"] | null;
            /** @description Errors related to requested service, if any */
            errors?: components["schemas"]["ErrorType"][] | null;
            /** @description Warnings related to the requested service, if any. Warnings could explain why some parts of the requested data is missing */
            warnings?: components["schemas"]["WarningType"][] | null;
        };
        QuickpackSpecificEdiParametersType: {
            upsSpecificEdiParameters?: components["schemas"]["UpsSpecificEdiParametersType"] | null;
            orderStartTime?: string | null;
        };
        RouteInformationType: {
            /** @description Route id */
            routeId: string | null;
            /** @description Route name */
            routeName: string | null;
        };
        SameDayDeliveryType: {
            /**
             * Format: dd.MM.yyyy
             * @description Formatted delivery date
             */
            formattedDeliveryDate: string | null;
            deliveryDate: components["schemas"]["ExpectedDeliveryDateType"] | null;
            routeInformation?: components["schemas"]["RouteInformationType"] | null;
        };
        Shipping_guide_response: {
            /** @description List of consignments */
            consignments?: components["schemas"]["ConsignmentOutputType"][] | null;
            /** @description Request unique id */
            uniqueId?: string | null;
        };
        TimeSlotType: {
            startTime: components["schemas"]["DayTimeType"] | null;
            endTime: components["schemas"]["DayTimeType"] | null;
        };
        TransportLegEnvironmentalDataType: {
            /**
             * @description Transport leg
             * @enum {string|null}
             */
            transportLeg: "LAST_MILE" | "LINE_HAUL" | "FIRST_MILE" | null;
            /** @description If true, shipment is transported by fossil free vehicles on this leg */
            fossilFree?: boolean | null;
            /** @description If true, shipment that is transported is nordic swan eco labeled */
            nordicSwanEcoLabel?: boolean | null;
            /** @description Human readable description */
            description?: string | null;
            details?: components["schemas"]["EnvironmentalDataDetailsType"] | null;
        };
        UpsSpecificEdiParametersType: {
            upsServiceTitle: string | null;
            upsRoutingCode: string | null;
            upsRoutingCodeVersion: string | null;
            upsAccountNumber: string | null;
            upsServiceIndicator: string | null;
            leg1CustomerNumber: string | null;
            leg1TransportServiceProvider: string | null;
            stateProvinceCounty: string | null;
            bringStreamIndicator: string | null;
            upsServiceIcon: string | null;
            upsClassOfService: string | null;
            upsBillingOption: string | null;
            upsDocumentationIndicator1: string | null;
            upsDocumentationIndicator2: string | null;
            upsSignatureRequiredString: string | null;
        };
        WarningType: {
            /**
             * @description Warning code
             * @enum {string|null}
             */
            code: "NO_EXPECTED_DELIVERY" | "NO_PRICE_INFORMATION" | "ADDITIONAL_SERVICE_NOT_APPLICABLE" | "ESTIMATED_DELIVERY_TIME_NOT_FOUND" | "INCORRECT_FLAG_SET_FOR_ESTIMATED_DELIVERY_TIME" | "ESTIMATED_DELIVERY_TIME_NOT_AVAILABLE" | "OUTSIDE_STANDARD_COVERAGE_AREA_FOR_PRODUCT" | "ESTIMATED_ARRIVAL_TIME_NOT_FOUND" | "ESTIMATED_ARRIVAL_TIME_NOT_AVAILABLE" | "ADDRESS_NOT_MATCHED" | "SVALBARD_POSSIBLE_DELAY" | "SPECIAL_CARGO_LIMITS_EXCEEDED" | "SPECIAL_HANDLING_LIMITS_EXCEEDED" | "EXPECTED_DELIVERY_NOT_AVAILABLE_WITHOUT_ADDRESS" | "EXPECTED_DELIVERY_NOT_AVAILABLE_UNKNOWN_ADDRESS" | "NO_ENVIRONMENTAL_DATA" | "PARCEL_LOCKER_UNIT_ID_MANDATORY_FOR_ESTIMATED_DELIVERY_TIME" | "LEADTIME_NOT_FOUND" | "REQUIRES_WEIGHT_FOR_PRICE_CALCULATION" | "NO_ALTERNATIVE_DATES" | null;
            /** @description Human-readable description of the warning */
            description: string | null;
        };
        Errors: {
            fieldErrors: components["schemas"]["FieldError"][] | null;
        };
        FieldError: {
            /** @enum {string} */
            code?: "NOT_FOUND" | "FORBIDDEN" | "CONFLICT" | "UNAUTHORIZED" | "INVALID_ARGUMENT" | "INVALID_MEASUREMENTS" | "INTERNAL_ERROR";
            message: string | null;
            field: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    products: {
        parameters: {
            query?: never;
            header: {
                /** @description Mybring login ID */
                "X-MyBring-API-Uid": string;
                /** @description Your user's API key */
                "X-MyBring-API-Key": string;
                /** @description Desired output media type */
                Accept?: "application/json" | "application/xml";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Shipping_guide_request"];
                "application/xml": components["schemas"]["Shipping_guide_request"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipping_guide_response"];
                    "application/xml": components["schemas"]["Shipping_guide_response"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Errors"];
                    "application/xml": components["schemas"]["Errors"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example Request rate cannot exceed 60 requests per 1 second */
                    "text/plain": string;
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Errors"];
                    "application/xml": components["schemas"]["Errors"];
                };
            };
        };
    };
}
